vlib questa_lib/work
vlib questa_lib/msim

vlib questa_lib/msim/xilinx_vip
vlib questa_lib/msim/xpm
vlib questa_lib/msim/axi_infrastructure_v1_1_0
vlib questa_lib/msim/axi_vip_v1_1_21
vlib questa_lib/msim/processing_system7_vip_v1_0_23
vlib questa_lib/msim/xil_defaultlib
vlib questa_lib/msim/proc_sys_reset_v5_0_17
vlib questa_lib/msim/xlconstant_v1_1_10
vlib questa_lib/msim/smartconnect_v1_0
vlib questa_lib/msim/axi_register_slice_v2_1_35
vlib questa_lib/msim/xpm_cdc_gen_v1_0_5

vmap xilinx_vip questa_lib/msim/xilinx_vip
vmap xpm questa_lib/msim/xpm
vmap axi_infrastructure_v1_1_0 questa_lib/msim/axi_infrastructure_v1_1_0
vmap axi_vip_v1_1_21 questa_lib/msim/axi_vip_v1_1_21
vmap processing_system7_vip_v1_0_23 questa_lib/msim/processing_system7_vip_v1_0_23
vmap xil_defaultlib questa_lib/msim/xil_defaultlib
vmap proc_sys_reset_v5_0_17 questa_lib/msim/proc_sys_reset_v5_0_17
vmap xlconstant_v1_1_10 questa_lib/msim/xlconstant_v1_1_10
vmap smartconnect_v1_0 questa_lib/msim/smartconnect_v1_0
vmap axi_register_slice_v2_1_35 questa_lib/msim/axi_register_slice_v2_1_35
vmap xpm_cdc_gen_v1_0_5 questa_lib/msim/xpm_cdc_gen_v1_0_5

vlog -work xilinx_vip -64 -incr -mfcu  -sv -L axi_vip_v1_1_21 -L smartconnect_v1_0 -L processing_system7_vip_v1_0_23 -L xilinx_vip "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/axi_vip_if.sv" \
"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/clk_vip_if.sv" \
"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/rst_vip_if.sv" \

vlog -work xpm -64 -incr -mfcu  -sv -L axi_vip_v1_1_21 -L smartconnect_v1_0 -L processing_system7_vip_v1_0_23 -L xilinx_vip "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
"/tools/Xilinx/2025.1/Vivado/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
"/tools/Xilinx/2025.1/Vivado/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
"/tools/Xilinx/2025.1/Vivado/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

vcom -work xpm -64 -93  \
"/tools/Xilinx/2025.1/data/ip/xpm/xpm_VCOMP.vhd" \

vlog -work axi_infrastructure_v1_1_0 -64 -incr -mfcu  "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
"../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \

vlog -work axi_vip_v1_1_21 -64 -incr -mfcu  -sv -L axi_vip_v1_1_21 -L smartconnect_v1_0 -L processing_system7_vip_v1_0_23 -L xilinx_vip "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
"../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/f16f/hdl/axi_vip_v1_1_vl_rfs.sv" \

vlog -work processing_system7_vip_v1_0_23 -64 -incr -mfcu  -sv -L axi_vip_v1_1_21 -L smartconnect_v1_0 -L processing_system7_vip_v1_0_23 -L xilinx_vip "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
"../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/6cfa/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib -64 -incr -mfcu  "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_processing_system7_0_1/sim/design_1_processing_system7_0_1.v" \
"../../../bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/sim/ila_pixclk.v" \
"../../../bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/sim/ila_refclk.v" \

vcom -work xil_defaultlib -64 -93  \
"../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/f99d/src/DVI_Constants.vhd" \
"../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/f99d/src/ChannelBond.vhd" \
"../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/f99d/src/SyncAsync.vhd" \
"../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/f99d/src/GlitchFilter.vhd" \
"../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/f99d/src/TWI_SlaveCtl.vhd" \
"../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/f99d/src/EEPROM_8b.vhd" \
"../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/f99d/src/InputSERDES.vhd" \
"../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/f99d/src/PhaseAlign.vhd" \
"../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/f99d/src/ResyncToBUFG.vhd" \
"../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/f99d/src/SyncAsyncReset.vhd" \
"../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/f99d/src/SyncBase.vhd" \
"../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/f99d/src/TMDS_Clocking.vhd" \
"../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/f99d/src/TMDS_Decoder.vhd" \
"../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/f99d/src/dvi2rgb.vhd" \
"../../../bd/design_1/ip/design_1_dvi2rgb_0_0/sim/design_1_dvi2rgb_0_0.vhd" \
"../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/d57c/src/ClockGen.vhd" \
"../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/d57c/src/OutputSERDES.vhd" \
"../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/d57c/src/TMDS_Encoder.vhd" \
"../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/d57c/src/rgb2dvi.vhd" \
"../../../bd/design_1/ip/design_1_rgb2dvi_0_0/sim/design_1_rgb2dvi_0_0.vhd" \

vlog -work xil_defaultlib -64 -incr -mfcu  "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_clk_wiz.v" \
"../../../bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.v" \
"../../../bd/design_1/ip/design_1_fir_wrapper_0_0/sim/design_1_fir_wrapper_0_0.v" \
"../../../bd/design_1/ip/design_1_tristate_0_0/sim/design_1_tristate_0_0.v" \
"../../../bd/design_1/ip/design_1_tristate_0_1/sim/design_1_tristate_0_1.v" \

vcom -work proc_sys_reset_v5_0_17 -64 -93  \
"../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/9438/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -64 -93  \
"../../../bd/design_1/ip/design_1_rst_ps7_0_100M_0/sim/design_1_rst_ps7_0_100M_0.vhd" \

vlog -work xil_defaultlib -64 -incr -mfcu  "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
"../../../bd/design_1/ipshared/5aca/hdl/fir_interface_slave_lite_v1_0_S00_AXI.v" \
"../../../bd/design_1/ipshared/5aca/hdl/fir_interface.v" \
"../../../bd/design_1/ip/design_1_fir_interface_0_0/sim/design_1_fir_interface_0_0.v" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/sim/bd_afc3.v" \

vlog -work xlconstant_v1_1_10 -64 -incr -mfcu  "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
"../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/a165/hdl/xlconstant_v1_1_vl_rfs.v" \

vlog -work xil_defaultlib -64 -incr -mfcu  "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_0/sim/bd_afc3_one_0.v" \

vcom -work xil_defaultlib -64 -93  \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_1/sim/bd_afc3_psr_aclk_0.vhd" \

vlog -work smartconnect_v1_0 -64 -incr -mfcu  -sv -L axi_vip_v1_1_21 -L smartconnect_v1_0 -L processing_system7_vip_v1_0_23 -L xilinx_vip "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
"../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/sc_util_v1_0_vl_rfs.sv" \
"../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/d800/hdl/sc_mmu_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib -64 -incr -mfcu  -sv -L axi_vip_v1_1_21 -L smartconnect_v1_0 -L processing_system7_vip_v1_0_23 -L xilinx_vip "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_2/sim/bd_afc3_s00mmu_0.sv" \

vlog -work smartconnect_v1_0 -64 -incr -mfcu  -sv -L axi_vip_v1_1_21 -L smartconnect_v1_0 -L processing_system7_vip_v1_0_23 -L xilinx_vip "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
"../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/2da8/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib -64 -incr -mfcu  -sv -L axi_vip_v1_1_21 -L smartconnect_v1_0 -L processing_system7_vip_v1_0_23 -L xilinx_vip "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_3/sim/bd_afc3_s00tr_0.sv" \

vlog -work smartconnect_v1_0 -64 -incr -mfcu  -sv -L axi_vip_v1_1_21 -L smartconnect_v1_0 -L processing_system7_vip_v1_0_23 -L xilinx_vip "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
"../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/dce3/hdl/sc_si_converter_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib -64 -incr -mfcu  -sv -L axi_vip_v1_1_21 -L smartconnect_v1_0 -L processing_system7_vip_v1_0_23 -L xilinx_vip "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_4/sim/bd_afc3_s00sic_0.sv" \

vlog -work smartconnect_v1_0 -64 -incr -mfcu  -sv -L axi_vip_v1_1_21 -L smartconnect_v1_0 -L processing_system7_vip_v1_0_23 -L xilinx_vip "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
"../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/cef3/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib -64 -incr -mfcu  -sv -L axi_vip_v1_1_21 -L smartconnect_v1_0 -L processing_system7_vip_v1_0_23 -L xilinx_vip "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_5/sim/bd_afc3_s00a2s_0.sv" \

vlog -work smartconnect_v1_0 -64 -incr -mfcu  -sv -L axi_vip_v1_1_21 -L smartconnect_v1_0 -L processing_system7_vip_v1_0_23 -L xilinx_vip "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
"../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/sc_node_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib -64 -incr -mfcu  -sv -L axi_vip_v1_1_21 -L smartconnect_v1_0 -L processing_system7_vip_v1_0_23 -L xilinx_vip "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_6/sim/bd_afc3_sarn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_7/sim/bd_afc3_srn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_8/sim/bd_afc3_sawn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_9/sim/bd_afc3_swn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_10/sim/bd_afc3_sbn_0.sv" \

vlog -work smartconnect_v1_0 -64 -incr -mfcu  -sv -L axi_vip_v1_1_21 -L smartconnect_v1_0 -L processing_system7_vip_v1_0_23 -L xilinx_vip "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
"../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/7f4f/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib -64 -incr -mfcu  -sv -L axi_vip_v1_1_21 -L smartconnect_v1_0 -L processing_system7_vip_v1_0_23 -L xilinx_vip "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_11/sim/bd_afc3_m00s2a_0.sv" \

vlog -work smartconnect_v1_0 -64 -incr -mfcu  -sv -L axi_vip_v1_1_21 -L smartconnect_v1_0 -L processing_system7_vip_v1_0_23 -L xilinx_vip "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
"../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/0133/hdl/sc_exit_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib -64 -incr -mfcu  -sv -L axi_vip_v1_1_21 -L smartconnect_v1_0 -L processing_system7_vip_v1_0_23 -L xilinx_vip "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_12/sim/bd_afc3_m00e_0.sv" \

vlog -work smartconnect_v1_0 -64 -incr -mfcu  -sv -L axi_vip_v1_1_21 -L smartconnect_v1_0 -L processing_system7_vip_v1_0_23 -L xilinx_vip "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
"../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/3718/hdl/sc_switchboard_v1_0_vl_rfs.sv" \

vlog -work axi_register_slice_v2_1_35 -64 -incr -mfcu  "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
"../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/c5b7/hdl/axi_register_slice_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib -64 -incr -mfcu  -sv -L axi_vip_v1_1_21 -L smartconnect_v1_0 -L processing_system7_vip_v1_0_23 -L xilinx_vip "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_axi_smc_0/sim/design_1_axi_smc_0.sv" \

vlog -work xpm_cdc_gen_v1_0_5 -64 -incr -mfcu  "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
"../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/5f71/hdl/xpm_cdc_gen_v1_0_vl_rfs.v" \

vlog -work xil_defaultlib -64 -incr -mfcu  "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3_fir.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_xpm_cdc_gen_0_0/sim/design_1_xpm_cdc_gen_0_0.v" \
"../../../bd/design_1/ip/design_1_xpm_cdc_gen_0_1/sim/design_1_xpm_cdc_gen_0_1.v" \
"../../../bd/design_1/ip/design_1_xpm_cdc_gen_0_2/sim/design_1_xpm_cdc_gen_0_2.v" \
"../../../bd/design_1/ip/design_1_xpm_cdc_gen_0_3/sim/design_1_xpm_cdc_gen_0_3.v" \
"../../../bd/design_1/ip/design_1_ila_0_1/sim/design_1_ila_0_1.v" \
"../../../bd/design_1/sim/design_1.v" \

vlog -work xil_defaultlib \
"glbl.v"

