# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/cathyhu3/s965/pz2/lab2/base.xdc

# Block Designs: bd/spi_max/spi_max.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_max || ORIG_REF_NAME==spi_max} -quiet] -quiet

# IP: bd/spi_max/ip/spi_max_processing_system7_0_0/spi_max_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_max_processing_system7_0_0 || ORIG_REF_NAME==spi_max_processing_system7_0_0} -quiet] -quiet

# IP: bd/spi_max/ip/spi_max_disp_interface_0_0/spi_max_disp_interface_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_max_disp_interface_0_0 || ORIG_REF_NAME==spi_max_disp_interface_0_0} -quiet] -quiet

# IP: bd/spi_max/ip/spi_max_axi_smc_0/spi_max_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_max_axi_smc_0 || ORIG_REF_NAME==spi_max_axi_smc_0} -quiet] -quiet

# Block Designs: /home/cathyhu3/s965/pz2/lab2_spi_maxdisplay/lab2_spi_maxdisplay.gen/sources_1/bd/spi_max/ip/spi_max_axi_smc_0/bd_0/bd_e4dc.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/cathyhu3/s965/pz2/lab2_spi_maxdisplay/lab2_spi_maxdisplay.gen/sources_1/bd/spi_max/ip/spi_max_axi_smc_0/bd_0/ip/ip_0/bd_e4dc_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/cathyhu3/s965/pz2/lab2_spi_maxdisplay/lab2_spi_maxdisplay.gen/sources_1/bd/spi_max/ip/spi_max_axi_smc_0/bd_0/ip/ip_1/bd_e4dc_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/cathyhu3/s965/pz2/lab2_spi_maxdisplay/lab2_spi_maxdisplay.gen/sources_1/bd/spi_max/ip/spi_max_axi_smc_0/bd_0/ip/ip_2/bd_e4dc_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/cathyhu3/s965/pz2/lab2_spi_maxdisplay/lab2_spi_maxdisplay.gen/sources_1/bd/spi_max/ip/spi_max_axi_smc_0/bd_0/ip/ip_3/bd_e4dc_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/cathyhu3/s965/pz2/lab2_spi_maxdisplay/lab2_spi_maxdisplay.gen/sources_1/bd/spi_max/ip/spi_max_axi_smc_0/bd_0/ip/ip_4/bd_e4dc_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/cathyhu3/s965/pz2/lab2_spi_maxdisplay/lab2_spi_maxdisplay.gen/sources_1/bd/spi_max/ip/spi_max_axi_smc_0/bd_0/ip/ip_5/bd_e4dc_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/cathyhu3/s965/pz2/lab2_spi_maxdisplay/lab2_spi_maxdisplay.gen/sources_1/bd/spi_max/ip/spi_max_axi_smc_0/bd_0/ip/ip_6/bd_e4dc_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/cathyhu3/s965/pz2/lab2_spi_maxdisplay/lab2_spi_maxdisplay.gen/sources_1/bd/spi_max/ip/spi_max_axi_smc_0/bd_0/ip/ip_7/bd_e4dc_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/cathyhu3/s965/pz2/lab2_spi_maxdisplay/lab2_spi_maxdisplay.gen/sources_1/bd/spi_max/ip/spi_max_axi_smc_0/bd_0/ip/ip_8/bd_e4dc_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/cathyhu3/s965/pz2/lab2_spi_maxdisplay/lab2_spi_maxdisplay.gen/sources_1/bd/spi_max/ip/spi_max_axi_smc_0/bd_0/ip/ip_9/bd_e4dc_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/cathyhu3/s965/pz2/lab2_spi_maxdisplay/lab2_spi_maxdisplay.gen/sources_1/bd/spi_max/ip/spi_max_axi_smc_0/bd_0/ip/ip_10/bd_e4dc_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/cathyhu3/s965/pz2/lab2_spi_maxdisplay/lab2_spi_maxdisplay.gen/sources_1/bd/spi_max/ip/spi_max_axi_smc_0/bd_0/ip/ip_11/bd_e4dc_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/cathyhu3/s965/pz2/lab2_spi_maxdisplay/lab2_spi_maxdisplay.gen/sources_1/bd/spi_max/ip/spi_max_axi_smc_0/bd_0/ip/ip_12/bd_e4dc_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/spi_max/ip/spi_max_rst_ps7_0_100M_0/spi_max_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_max_rst_ps7_0_100M_0 || ORIG_REF_NAME==spi_max_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/spi_max/ip/spi_max_spi_tx_w_0_0/spi_max_spi_tx_w_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_max_spi_tx_w_0_0 || ORIG_REF_NAME==spi_max_spi_tx_w_0_0} -quiet] -quiet

# XDC: /home/cathyhu3/s965/pz2/lab2_spi_maxdisplay/lab2_spi_maxdisplay.gen/sources_1/bd/spi_max/ip/spi_max_processing_system7_0_0/spi_max_processing_system7_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==spi_max_processing_system7_0_0 || ORIG_REF_NAME==spi_max_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/cathyhu3/s965/pz2/lab2_spi_maxdisplay/lab2_spi_maxdisplay.gen/sources_1/bd/spi_max/ip/spi_max_axi_smc_0/bd_0/ip/ip_1/bd_e4dc_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/cathyhu3/s965/pz2/lab2_spi_maxdisplay/lab2_spi_maxdisplay.gen/sources_1/bd/spi_max/ip/spi_max_axi_smc_0/bd_0/ip/ip_5/bd_e4dc_s00a2s_0_ooc.xdc

# XDC: /home/cathyhu3/s965/pz2/lab2_spi_maxdisplay/lab2_spi_maxdisplay.gen/sources_1/bd/spi_max/ip/spi_max_axi_smc_0/bd_0/ip/ip_6/bd_e4dc_sarn_0_ooc.xdc

# XDC: /home/cathyhu3/s965/pz2/lab2_spi_maxdisplay/lab2_spi_maxdisplay.gen/sources_1/bd/spi_max/ip/spi_max_axi_smc_0/bd_0/ip/ip_7/bd_e4dc_srn_0_ooc.xdc

# XDC: /home/cathyhu3/s965/pz2/lab2_spi_maxdisplay/lab2_spi_maxdisplay.gen/sources_1/bd/spi_max/ip/spi_max_axi_smc_0/bd_0/ip/ip_8/bd_e4dc_sawn_0_ooc.xdc

# XDC: /home/cathyhu3/s965/pz2/lab2_spi_maxdisplay/lab2_spi_maxdisplay.gen/sources_1/bd/spi_max/ip/spi_max_axi_smc_0/bd_0/ip/ip_9/bd_e4dc_swn_0_ooc.xdc

# XDC: /home/cathyhu3/s965/pz2/lab2_spi_maxdisplay/lab2_spi_maxdisplay.gen/sources_1/bd/spi_max/ip/spi_max_axi_smc_0/bd_0/ip/ip_10/bd_e4dc_sbn_0_ooc.xdc

# XDC: /home/cathyhu3/s965/pz2/lab2_spi_maxdisplay/lab2_spi_maxdisplay.gen/sources_1/bd/spi_max/ip/spi_max_axi_smc_0/bd_0/ip/ip_11/bd_e4dc_m00s2a_0_ooc.xdc

# XDC: /home/cathyhu3/s965/pz2/lab2_spi_maxdisplay/lab2_spi_maxdisplay.gen/sources_1/bd/spi_max/ip/spi_max_axi_smc_0/ooc.xdc

# XDC: /home/cathyhu3/s965/pz2/lab2_spi_maxdisplay/lab2_spi_maxdisplay.gen/sources_1/bd/spi_max/ip/spi_max_axi_smc_0/smartconnect.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==spi_max_axi_smc_0 || ORIG_REF_NAME==spi_max_axi_smc_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/cathyhu3/s965/pz2/lab2_spi_maxdisplay/lab2_spi_maxdisplay.gen/sources_1/bd/spi_max/ip/spi_max_rst_ps7_0_100M_0/spi_max_rst_ps7_0_100M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==spi_max_rst_ps7_0_100M_0 || ORIG_REF_NAME==spi_max_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/cathyhu3/s965/pz2/lab2_spi_maxdisplay/lab2_spi_maxdisplay.gen/sources_1/bd/spi_max/spi_max_ooc.xdc
